/* eslint-disable @next/next/no-img-element -- KYUTE production stills and original YouTube posters. */
"use client";
import { useEffect, useRef, useState } from "react";
import HeroVideo from "./HeroVideo";
import CountUp from "./CountUp";
import CultureMaterialForm from "./CultureMaterialForm";
import CultureProblem from "./CultureProblem";
import CultureEngine from "./CultureEngine";
import CultureFormats from "./CultureFormats";
import { cultureFilms as films, cultureFrames as frames } from "./culture-media";
const Arrow=()=> <span aria-hidden="true">↗</span>;
const Play=()=> <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7Z"/></svg>;
function GuideLink({children="サービス資料を見る",className=""}:{children?:React.ReactNode;className?:string}){return <a href="#download" className={`cs-button ${className}`}>{children}<Arrow/></a>;}
export default function CultureLP(){
 const [playing,setPlaying]=useState<number|null>(null),[sticky,setSticky]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{const update=()=>{const download=document.getElementById('download');setSticky(scrollY>500&&(download?.getBoundingClientRect().top??0)>innerHeight*.8);};window.addEventListener('scroll',update,{passive:true});update();return()=>window.removeEventListener('scroll',update);},[]);
 useEffect(()=>{const el=dialog.current;if(playing!==null&&el&&!el.open){el.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};}},[playing]);
 function openFilm(index:number){trigger.current=document.activeElement as HTMLElement;setPlaying(index);}
 function closeFilm(){dialog.current?.close();setPlaying(null);trigger.current?.focus();}
 return <div id="culture-lp">
  <a className="cs-skip" href="#main">本文へスキップ</a>
  <header className="cs-header"><a href="#top" className="cs-logo" aria-label="KYUTE トップへ">KYUTE<span>.</span></a><p>採用に、カルチャーという選ばれ方を。</p><nav aria-label="メインナビゲーション"><a href="#works">制作映像</a><a href="#operation">支援内容</a><GuideLink/></nav></header>
  <main id="main">
   <section id="top" className="cs-hero"><HeroVideo suspended={playing!==null}/><div className="cs-hero-shade"/><div className="cs-hero-content"><p className="cs-hero-service">カルチャー訴求特化の、<br/>採用YouTube運用代行。</p><h1>カルチャーは、<br/>文字では<br/><em>伝わらない。</em></h1><div className="cs-hero-bottom"><p>求人票では伝わらない、<br/>人・仕事・会社の空気まで。</p><GuideLink>採用YouTubeのサービス資料を見る</GuideLink></div></div><a className="cs-hero-watch" href="#works"><span><Play/></span>制作映像を見る</a></section>
   <div className="cs-intro-line"><p>その会社らしさを、採用の力に。</p><span>採用戦略 <i>／</i> コンテンツ企画 <i>／</i> 映像制作 <i>／</i> YouTube運用</span></div>
   <CultureProblem/>
   <section className="cs-data cs-section" id="culture"><div className="cs-wrap"><div className="cs-data-heading"><p className="cs-eyebrow">入社の決め手は、条件だけじゃない。</p><h2>人は、<br/>人に惹かれる。</h2><p>「誰と、どんな空気の中で働くか」。<br/>それは、会社を選ぶ理由になっている。</p></div><div className="cs-data-primary"><p>入社予定先を決めた理由</p><CountUp value={42.4}/><h3>社員の雰囲気・人柄が<br/>自分に合っている。</h3></div><div className="cs-data-secondary"><CountUp value={37.5}/><p>社風が自分に合っている。</p></div><details className="cs-source"><summary>調査の対象・出典を見る <span>＋</span></summary><p>マイナビ「2025年卒 大学生 活動実態調査（6月15日）」。2024年6月調査、入社先決定者1,898人／複数回答・ウエイトバック集計。採用YouTubeの効果を測った数値ではありません。</p><a href="https://career-research.mynavi.jp/wp-content/uploads/2024/06/s-nainaitei-0615.pdf" target="_blank" rel="noopener noreferrer">調査原典を読む ↗</a></details></div></section>
   <section className="cs-language cs-section" id="youtube"><div className="cs-wrap"><div className="cs-section-opening"><p className="cs-eyebrow">見れば、想像できることがある。</p><h2>だから、<br/>採用YouTube。</h2><p>声も、表情も、仕事のリズムも。<br/>「ここで働く自分」を想像できる情報を、<br/>見たくなるコンテンツに。</p></div><div className="cs-frame-editorial"><figure className="cs-language-person"><img src={frames.smile} width="1280" height="720" alt="会話の中で自然な笑顔を見せる出演者" loading="lazy"/><figcaption><span>表情から、人柄が見える。</span><b>PEOPLE.</b></figcaption></figure><figure className="cs-language-work"><img src={frames.work} width="1280" height="720" alt="カフェ厨房で働く姿" loading="lazy"/><figcaption><span>一日から、仕事が見える。</span><b>WORK.</b></figcaption></figure><figure className="cs-language-story"><img src={frames.story} width="1280" height="720" alt="自分の仕事について語る起業家" loading="lazy"/><figcaption><span>選択から、想いが見える。</span><b>STORY.</b></figcaption></figure><p className="cs-frame-message">人を知る。<br/>仕事を知る。<br/><em>会社を、好きになる。</em><small>KYUTE自社メディアの制作映像より</small></p></div></div></section>
   <section className="cs-works cs-section" id="works"><div className="cs-wrap"><div className="cs-works-heading"><div><p className="cs-eyebrow">KYUTEの制作作品</p><h2>その人の選択に、<br/>物語がある。</h2></div><p>企画し、聞き、撮り、編集する。<br/>私たちの表現を、まずは映像で。<span className="cs-channel-link">自社メディア「運動部のシゴト。」</span></p></div><div className="cs-work-grid">{films.map((film,index)=><article className={`cs-work cs-work-${index+1}`} key={film.id}><button type="button" className="cs-work-image" onClick={()=>openFilm(index)} aria-label={`${film.original}を再生`}><img src={film.still} width="1280" height="720" alt={film.original} loading="lazy"/><span className="cs-work-play"><Play/></span><span className="cs-work-duration">{film.duration}</span><span className="cs-work-number">0{index+1}</span></button><div className="cs-work-caption"><h3>{film.name}</h3><p>{film.statement}</p><span>{film.category}</span></div></article>)}</div><p className="cs-work-note">掲載作品はKYUTE運営「運動部のシゴト。」の映像です。<br className="cs-mobile-break"/>企画・撮影・編集の表現例として掲載しており、顧客企業の採用導入事例ではありません。</p></div></section>
   <section className="cs-why cs-section" id="why-kyute"><div className="cs-wrap"><div className="cs-section-opening"><p className="cs-eyebrow">採用の視点を、クリエイティブに。</p><h2>採用を考える。<br/>表現をつくる。<br/>届け続ける。</h2><p>惹かれる理由から、見たくなる企画へ。<br/>KYUTEは、この3つをつなぐチームです。</p></div><div className="cs-disciplines">{[{en:'RECRUITING',jp:'誰に、何が響くのか。',copy:'採用ターゲットを理解し、人・仕事・カルチャーのどこに惹かれるのかを設計する。'},{en:'CREATIVE',jp:'続きが、見たくなる。',copy:'密着、インタビュー、対談。伝えたいことを、見てもらえるコンテンツに変える。'},{en:'OPERATION',jp:'公開を、次のはじまりに。',copy:'視聴データと採用現場の反応から、次の企画を考える。届け方を、継続して磨く。'}].map((item,i)=><div className="cs-discipline" key={item.en}><span className="cs-discipline-index">0{i+1}</span><strong>{item.en}</strong><div><h3>{item.jp}</h3><p>{item.copy}</p></div>{i<2&&<span className="cs-times" aria-hidden="true">×</span>}</div>)}<div className="cs-convergence"><span aria-hidden="true">↓</span><p>カルチャーで、<br className="cs-mobile-break"/><strong>選ばれる採用。</strong></p></div></div></div></section>
   <CultureEngine/>
   <CultureFormats/>
   <section className="cs-experience cs-section" id="experience"><div className="cs-wrap"><div className="cs-experience-title"><p className="cs-eyebrow">応募数の、その先へ。</p><h2>応募する前に、<br/>志望度を上げる。</h2><p>「条件が合う」から、「ここで働きたい」へ。<br/>お互いを知ったうえで、出会える採用を。</p></div><div className="cs-experience-pair"><div className="cs-experience-before"><p className="cs-experience-label">条件を中心に、会社を知る</p><div className="cs-mini-job"><span>募集要項</span><div>仕事内容 <i/></div><div>給与・待遇 <i/></div><div>勤務地 <i/></div></div><p className="cs-feeling">どんな人と、<br/>働くんだろう。</p><ol><li>会社・求人を知る</li><li>条件を見る</li><li>応募する</li><li>面接でカルチャーを知る</li></ol></div><div className="cs-experience-after"><img src={frames.smile} width="1280" height="720" alt="出演者の自然な表情。映像で人を知る体験の参考" loading="lazy"/><p className="cs-experience-label">カルチャーまで知って、会社を選ぶ</p><p className="cs-feeling">この人たちと、<br/>働いてみたい。</p><ol><li>YouTubeを見る</li><li>人・カルチャーを知る</li><li>ここで働きたい</li><li>応募する</li></ol></div></div><div className="cs-video-data"><div><CountUp value={69}/><p>採用動画を見たいのは、<strong>「応募前」。</strong></p></div><details className="cs-source"><summary>調査の対象・出典を見る <span>＋</span></summary><p>エン転職ユーザー調査、2025年4月。調査全体1,393人／複数回答。69.0%は原典の69%を表示統一したものです。上の比較は採用コミュニケーションの設計例であり、個別企業の採用成果を示すものではありません。</p><a href="https://corp.en-japan.com/newsrelease/2025/41694.html" target="_blank" rel="noopener noreferrer">調査原典を読む ↗</a></details></div></div></section>
   <section className="cs-big-message"><p>その会社らしさが、いちばんの理由になる。</p><h2>「第一志望企業」に、<br/><span>躍り出よう。</span></h2><a href="#download" aria-label="サービス資料を見る"><Arrow/></a></section>
   <section className="cs-download cs-section" id="download"><div className="cs-wrap"><div className="cs-download-intro"><p className="cs-eyebrow">採用YouTubeのサービス資料</p><h2>その会社らしさを、<br/>採用の力に。</h2><p>どんな価値を届けるのか。どこまで頼めるのか。<br/>はじめるためのヒントを、ひとつの資料に。</p><div className="cs-guide-preview"><div className="cs-guide-book" aria-label="採用YouTube運用代行サービスガイドの表紙イメージ"><strong>KYUTE.</strong><span>その会社らしさを、<br/>採用の力に。</span><b>CULTURE<br/>IN FRAME.</b><small>採用YouTube運用代行<br/>サービスガイド</small></div><ol><li>人・仕事・空気を伝える価値</li><li>企画から改善までの支援範囲</li><li>導入準備と進め方</li></ol></div><p className="cs-caption">無料 / PDF・全3ページ</p></div><CultureMaterialForm/></div></section>
  </main>
  <footer className="cs-footer"><div><a href="#top" className="cs-logo">KYUTE<span>.</span></a><p>カルチャーを、採用コンテンツに。</p></div><nav aria-label="フッターナビゲーション"><a href="/about">会社概要 <Arrow/></a><a href="/contact">お問い合わせ <Arrow/></a></nav><small>© KYUTE合同会社</small><a className="cs-back-top" href="#top" aria-label="ページの先頭へ">↑</a></footer>
  <div className={`cs-mobile-cta ${sticky?'is-visible':''}`} aria-hidden={!sticky}><a href="#download" tabIndex={sticky?0:-1}>採用YouTubeのサービス資料を見る<Arrow/></a></div>
  <dialog className="cs-dialog" ref={dialog} aria-labelledby="video-dialog-title" onCancel={e=>{e.preventDefault();closeFilm();}} onClick={e=>{if(e.target===e.currentTarget)closeFilm();}}><div className="cs-dialog-top"><p id="video-dialog-title">{playing!==null?films[playing].original:'制作映像'}</p><button type="button" onClick={closeFilm} aria-label="動画を閉じる" autoFocus>×</button></div>{playing!==null&&<><iframe key={playing} src={`https://www.youtube-nocookie.com/embed/${films[playing].id}?autoplay=1&rel=0`} title={films[playing].original} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><div className="cs-dialog-bottom"><p>自社メディア「運動部のシゴト。」</p><a href={`https://www.youtube.com/watch?v=${films[playing].id}`} target="_blank" rel="noopener noreferrer">YouTubeで見る ↗</a></div></>}</dialog>
 </div>;
}
